<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VIHouse.Entities\VIHouse.Entities.csproj" />
    <ProjectReference Include="..\VIHouse.DataAccess\VIHouse.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Stripe.net" Version="52.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
